### ISSUE TITLE
["Request"] Add onError to Bracket 

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow#2018]
`Bracket` exposes several combinators to `guarantee` an `IO` being run no matter whether the `IO` failed, was cancelled or finished successfully.

An `onCancel` overload was added in #2017, this can be used as a reference to implement `onError` with the corresponding `BracketLaws` to ensure polymorphic behavior.

**Comment by abendt** [comment]
i had a try on this: https://github.com/abendt/arrow/tree/issues/2018
is it how it should be?

**Comment by aballano** [comment]
> i had a try on this: https://github.com/abendt/arrow/tree/issues/2018
> is it how it should be?

Yes indeed 👍 If you wanna raise a PR I can take a look

**Comment by aballano** [comment]
Although @nomisRev do we really need the redeclaration for IO? I tested and one can use the generated extension over Bracket as it's suggested by the IDE

**Comment by abendt** [comment]
> Yes indeed 👍 If you wanna raise a PR I can take a look

done

**Comment by aballano** [comment]
Thank you @abendt for the contribution!! 🎉

**Comment by aballano** [comment]
Hi folks, I'd like ask 2 things about this implementation towards the next release:

* Shouldn’t onError signature be like this instead `fun <A> Kind<F, A>.onError(finalizer: (E) -> Kind<F, Unit>): Kind<F, A>` (note the given E)? Otherwise we don't provide much over what was the failure.
* Also [my comment above](https://github.com/arrow-kt/arrow/issues/2018#issuecomment-581136362): do we need the redeclaration in IO of both functions? I don't see it's doing anything on top of the implementation on Bracket

**Comment by 1Jajen1** [comment]
As for the first: I noted that as well https://github.com/arrow-kt/arrow/pull/2022#discussion_r373851135 seemed to cause some kind of issue when compiling. Not sure this still persists but I agree, it should offer `E` as a paramter if possible.

**Comment by abendt** [comment]
> * Shouldn’t onError signature be like this instead `fun <A> Kind<F, A>.onError(finalizer: (E) -> Kind<F, Unit>): Kind<F, A>` (note the given E)? Otherwise we don't provide much over what was the failure.

yes, i ran into some issues while trying that. didn't really understand what to do about it. i will prepare a branch later today so you can see

**Comment by aballano** [comment]
@abendt yes, you're right, sorry I already had created https://github.com/arrow-kt/arrow/pull/2040 and it indeed fails as you said, I can take a look to investigate as soon as I can (likely next week) :)

**Comment by abendt** [comment]
@aballano 😄 👍

**Comment by aballano** [comment]
Update: I need to check my changes but the tests now passed locally both from terminal and IntelliJ, let's see CI.
